### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tomoki0107** [tomoki0107/furima-29624#9]
自身のフリマアプリのURL:
Basic認証のID:tomoki
Basic認証のPassword:0340
出品者用のメールアドレス:asdf@ghj
出品者用のパスワード:111aaa
購入者用のメールアドレス:qwer@tyu
購入者用のパスワード:111aaa
購入用カードの番号:4242424242424242
購入用カードの期限:2(月)22(年)
購入用カードのセキュリティコード:123

**Comment by apapa1031** [comment]
野澤さんご提出ありがとうございます！
フリマアプリのURLが見当たらないのでURLを送っていただいてもよろしいでしょうか？

お手数をおかけしますが、よろしくお願い致します！

**Comment by tomoki0107** [comment]
フリマアプリのURL:https://furima-29624.herokuapp.com/
追記させていただきました！ご確認よろしくお願いします！

**Comment by Ayumuiwata** [comment]
野澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

【修正箇所】１点
・クレジットカード登録/変更ページが存在しない

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by tomoki0107** [comment]
コメントありがとうございます！
クレジットカードの登録、変更というのはフリマアプリのどの機能にあたるかを教えていただけますでしょうか？また、対応するビューなども自作して実装を行えばいいということでしょうか？お手数ですが、ご返信よろしくお願いします！

**Comment by apapa1031** [comment]
野澤さんご確認ありがとうございます！
再度、確認致しましたが、特に挙動に問題ございませんでしたのでLGTMとさせて頂きます！
混乱させるようなことを申し上げてしまい申し訳ございませんでした。

お疲れ様でした！
